import { Fighter } from './types';

export const MOCK_FIGHTERS: Fighter[] = [
  {
    id: '1',
    name: "Kyle 'Drywall' Smith",
    age: 24,
    height: "5'9\"",
    weight: "165 lbs",
    weightClass: "Welterweight",
    stance: "Orthodox",
    experience: "Street",
    bio: "Don't look at me wrong. I drink 4 Monsters before breakfast and I punch holes in walls for fun. Meet me at the 7-Eleven.",
    fightingStyle: "Berzerker",
    location: "Parking Lot B",
    stats: { strength: 70, speed: 85, anger: 100, durability: 60, crazy: 95 },
    imageUrl: "https://picsum.photos/400/600?random=1",
    distance: 2.1,
    wins: 15,
    losses: 2,
    winStreak: 5,
    badges: ["Verified", "High Energy"],
    compatibility: 85
  },
  {
    id: '2',
    name: "Big Deborah",
    age: 42,
    height: "5'4\"",
    weight: "210 lbs",
    weightClass: "Heavyweight",
    stance: "Southpaw",
    experience: "Amateur",
    bio: "I asked for NO pickles! If you step to me, bring a manager cause I'm about to file a complaint with my fists.",
    fightingStyle: "Heavyweight Tank",
    location: "Waffle House",
    stats: { strength: 90, speed: 30, anger: 85, durability: 100, crazy: 60 },
    imageUrl: "https://picsum.photos/400/600?random=2",
    distance: 0.5,
    wins: 42,
    losses: 0,
    winStreak: 42,
    badges: ["Undefeated", "Legend"],
    compatibility: 40
  },
  {
    id: '3',
    name: "Tyler Durden (Wish)",
    age: 29,
    height: "6'0\"",
    weight: "175 lbs",
    weightClass: "Middleweight",
    stance: "Switch",
    experience: "Pro",
    bio: "I make soap and I hurt people. Let's go to the basement. First rule is you don't talk about this app.",
    fightingStyle: "Underground",
    location: "Abandoned Warehouse",
    stats: { strength: 75, speed: 80, anger: 50, durability: 95, crazy: 90 },
    imageUrl: "https://picsum.photos/400/600?random=3",
    distance: 5.4,
    wins: 10,
    losses: 10,
    winStreak: 0,
    badges: ["Verified"],
    compatibility: 70
  },
  {
    id: '4',
    name: "Chad Thundercock",
    age: 22,
    height: "6'4\"",
    weight: "220 lbs",
    weightClass: "Heavyweight",
    stance: "Orthodox",
    experience: "Novice",
    bio: "My dad owns a dealership. I will sue you after I beat you up. Lacrosse stick is my weapon of choice.",
    fightingStyle: "Privileged Rage",
    location: "Country Club",
    stats: { strength: 85, speed: 70, anger: 40, durability: 70, crazy: 20 },
    imageUrl: "https://picsum.photos/400/600?random=4",
    distance: 1.2,
    wins: 3,
    losses: 8,
    winStreak: 0,
    badges: ["Rich Parents"],
    compatibility: 95
  },
  {
    id: '5',
    name: "Karen 'The Manager' Jones",
    age: 38,
    height: "5'6\"",
    weight: "140 lbs",
    weightClass: "Featherweight",
    stance: "Orthodox",
    experience: "Pro",
    bio: "Excuse me? EXCUSE ME? I have been waiting here for 5 minutes. Square up right now.",
    fightingStyle: "Screaming Banshee",
    location: "Retail Store",
    stats: { strength: 40, speed: 60, anger: 100, durability: 50, crazy: 100 },
    imageUrl: "https://picsum.photos/400/600?random=5",
    distance: 0.8,
    wins: 100,
    losses: 98,
    winStreak: 2,
    badges: ["Volume Striker"],
    compatibility: 10
  }
];